"""Actualizando migración

Revision ID: 00e4a2a919a2
Revises: a9bbc41605f0
Create Date: 2025-08-27 12:21:24.451466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e4a2a919a2'
down_revision: Union[str, None] = 'a9bbc41605f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
