"""Migracion a la base de datos

Revision ID: 072c9b8d9113
Revises: 13fd76a05632
Create Date: 2025-08-30 17:27:47.757149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072c9b8d9113'
down_revision: Union[str, None] = '13fd76a05632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
