"""Se insertó dato de prueba en la tabla producto

Revision ID: 13fd76a05632
Revises: 3a1a7e74051d
Create Date: 2025-08-30 02:49:24.158427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fd76a05632'
down_revision: Union[str, None] = '3a1a7e74051d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
