"""Se agregó un script.py para insertar datos en la tabla productos

Revision ID: 2a753f2515b7
Revises: b24959e29988
Create Date: 2025-08-25 16:09:49.725831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a753f2515b7'
down_revision: Union[str, None] = 'b24959e29988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
