"""Se creó una inserción de datos en la tabla producto

Revision ID: 2b2fd3894763
Revises: 79d89eb1b241
Create Date: 2025-08-25 15:53:25.059619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2fd3894763'
down_revision: Union[str, None] = '79d89eb1b241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
