"""Creación de tabla producto

Revision ID: 2b34ecfd7a80
Revises: 433fd66b808b
Create Date: 2025-08-30 02:17:36.190988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b34ecfd7a80'
down_revision: Union[str, None] = '433fd66b808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
