"""Inserción de datos en la tabla productosORM

Revision ID: a9bbc41605f0
Revises: 2a753f2515b7
Create Date: 2025-08-25 16:24:34.763689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bbc41605f0'
down_revision: Union[str, None] = '2a753f2515b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
