"""Se creó una inserción de datos en la tabla producto con el archivo script.py

Revision ID: b24959e29988
Revises: 07e408906778
Create Date: 2025-08-25 16:00:17.821918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24959e29988'
down_revision: Union[str, None] = '07e408906778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
