"""Se creó una inserción de datos en la tabla producto con el archivo script.py

Revision ID: 07e408906778
Revises: 2b2fd3894763
Create Date: 2025-08-25 15:57:37.400227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e408906778'
down_revision: Union[str, None] = '2b2fd3894763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
