"""Creando migración de tablas

Revision ID: d5af1b9c9a02
Revises: 2e641c5cd9cb
Create Date: 2025-09-01 02:38:55.927894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5af1b9c9a02'
down_revision: Union[str, None] = '2e641c5cd9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
