"""Nueva migración

Revision ID: e2c2d0c59d27
Revises: c0303e42f355
Create Date: 2025-09-03 14:00:49.713693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c2d0c59d27'
down_revision: Union[str, None] = 'c0303e42f355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('stock_minimo', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    # ### end Alembic commands ###
